url: https://shadowrz.github.io
baseurl: ''
lang: zh
title: å¸ƒå¶å›ğŸ­ / Dimension
description: From anything, to everything.
# logo: /assets/icons/icon.png
author:
  name: å¸ƒå¶å›
  email: shadowrz@disroot.org
  picture: https://github.com/ShadowRZ.png
  # twitter: <username>
social:
  name: å¸ƒå¶å›
  links:
    - https://github.com/ShadowRZ
    - https://plus.google.com/100337916368098194679
permalink: none
paginate: 20
paginate_path: /page/:num.html
# google_analytics: UA-XXXXXXXX-X
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  # - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-paginate
  # - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  # - jekyll-remote-theme
  # - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-mentions
theme: jekyll-theme-modernist
