url: https://shadowrz.github.io
baseurl: ''
lang: zh
title: å¸ƒå¶å›ğŸ­ / Dimension
description: From anything, to everything.
author:
  name: å¸ƒå¶å›
  picture: https://avatars.githubusercontent.com/ShadowRZ?s=256
social:
  name: å¸ƒå¶å›
  links:
    - https://github.com/ShadowRZ
image: /assets/images/default-card.png
permalink: /posts.d/:year/:month/:day/:title:output_ext
# google_analytics: UA-XXXXXXXX-X
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  # - jekyll-gist
  - jekyll-optional-front-matter
  # - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-redirect-from
  - jekyll-relative-links
  # - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-mentions
remote_theme: mmistakes/jekyll-theme-basically-basic
search: false
titles_from_headings:
  enabled: true
  strip_title: true
paginate: 5
paginate_path: /posts.d/page/:num:output_ext
